version: '3'
services:
  # api:
  #   image: luandromat
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command:
  #     ["/bin/sh", "-c", "npm install && npm cache clean --force && npm run dev"]
  #   ports:
  #     - "3333:3333"
  #   networks:
  #     - app-network
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: luandromat
      MYSQL_USER: dudee
      MYSQL_PASSWORD: indeed
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge